apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  namespace: emojivote
spec:
  template:
    spec:
      containers:
        - name: initdb
          image: us-central1-docker.pkg.dev/sandbox-367215/my-repository/initdb:v1.0
          env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  key: MYSQL_HOST
                  name: root-db-access
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: root-db-access
            - name: MYSQL_PASSWD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWD
                  name: root-db-access
      restartPolicy: Never
  backoffLimit: 4
